packages:
  - "apps/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  dtrace-provider: true
  esbuild: true
  prisma: true
  protobufjs: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.25'
  - '@expo/router-server@57.0.10'
  - babel-preset-expo@57.0.12
  - expo@57.0.23
  - expo-image-picker@57.0.18
